{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "triton-control.fullname" . }}
  labels:
    {{- include "triton-control.labels" . | nindent 4 }}
  {{- $annotations := dict -}}
  {{- with .Values.ingress.annotations }}
  {{- $annotations = merge $annotations . -}}
  {{- end }}
  {{- if .Values.ingress.proxyBodySize }}
  {{- $_ := set $annotations "nginx.ingress.kubernetes.io/proxy-body-size" (.Values.ingress.proxyBodySize | toString) -}}
  {{- end }}
  {{- if gt (len $annotations) 0 }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    -
      {{- with .host }}
      host: {{ . | quote }}
      {{- end }}
      http:
        paths:
          {{- range .paths.backend }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "triton-control.fullname" $ }}
                port:
                  name: api
          {{- end }}
          {{- range .paths.frontend }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "triton-control.fullname" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
