{{- if and (not .Values.app.existingSecret) .Values.app.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "triton-control.fullname" . }}-app
  labels:
    {{- include "triton-control.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.app.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
