{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "triton-control.serviceAccountName" . }}
  labels:
    {{- include "triton-control.labels" . | nindent 4 }}
{{- end }}