#!/usr/bin/env python3
"""Generate Triton semver -> release branch mapping from official GitHub releases.

Output:
  protobuff/triton_release_map.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parent
OUT_FILE = ROOT / "triton_release_map.py"
RELEASES_URL = "https://api.github.com/repos/triton-inference-server/server/releases?per_page=100"

RELEASE_NAME_PATTERN = re.compile(
    r"Release\s+(\d+\.\d+\.\d+)\s+corresponding to NGC container\s+(\d+\.\d+)"
)
SEMVER_PATTERN = re.compile(r"^2\.\d{2}\.\d+$")
CONTAINER_PATTERN = re.compile(r"^\d{2}\.\d{2}$")


def _fetch_mapping() -> dict[str, str]:
    with urlopen(RELEASES_URL, timeout=30) as response:
        payload = json.load(response)

    mapping: dict[str, str] = {}
    for release in payload:
        name = release.get("name") or ""
        match = RELEASE_NAME_PATTERN.search(name)
        if not match:
            continue

        semver = match.group(1)
        container = match.group(2)

        if not SEMVER_PATTERN.fullmatch(semver):
            continue
        if not CONTAINER_PATTERN.fullmatch(container):
            continue

        mapping[semver] = f"r{container}"

    return dict(sorted(mapping.items(), key=lambda item: tuple(int(x) for x in item[0].split("."))))


def _render(mapping: dict[str, str]) -> str:
    lines = [
        '"""Auto-generated Triton semver -> release branch mapping.',
        "",
        f"Generated by: {Path(__file__).name}",
        f"Source: {RELEASES_URL}",
        '"""',
        "",
        "TRITON_SEMVER_TO_RELEASE_BRANCH: dict[str, str] = {",
    ]

    for semver, release_branch in mapping.items():
        lines.append(f'    "{semver}": "{release_branch}",')

    lines.extend(["}", ""])
    return "\n".join(lines)


def main() -> int:
    mapping = _fetch_mapping()
    if not mapping:
        print("[fail] No matching Triton release mappings found")
        return 1

    OUT_FILE.write_text(_render(mapping), encoding="utf-8")
    print(f"[ok]   wrote {OUT_FILE}")
    print(f"[done] entries={len(mapping)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
